# Generated by Django 5.2.7 on 2026-07-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_team_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['starts', 'id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['event', 'name', 'id']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event'),
        ),
    ]
