# Generated by Django 5.2.7 on 2026-08-24 23:32

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_drop_team_users_and_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['starts', 'id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['event', 'name', 'id']},
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event'),
        ),
    ]
