FROM node:latest

RUN npm update -g npm

WORKDIR /code

COPY package.json package-lock.json ./
RUN npm install

# Support generate-allauth.sh
RUN apt update
RUN apt install -y python3 python3-yaml

CMD npm run dev
