"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

env = environ.Env()

# Whether or not the app is running production mode.
PRODUCTION = env.bool("DJANGO_PRODUCTION", default=False)

# Used internally by Django to decide how much debugging context is sent to the browser when a failure occurs.
# Cannot be True if PRODUCTION is True
DEBUG = False if PRODUCTION else env.bool("DJANGO_DEBUG", default=True)


def prod_required_env(key, default, method="str"):  # type: ignore[no-untyped-def]
    """
    Throw an exception if PRODUCTION is true and the environment key is not provided

    :type key: str
    :param key: Name of the environment variable to fetch
    :type default: any
    :param default: Default value for non-prod environments
    :type method: str
    :param method: django-environ instance method, used to type resulting data

    .. seealso::
       - `django-environ <https://github.com/joke2k/django-environ>`_
       - `django-environ supported types <https://github.com/joke2k/django-environ#supported-types>`_
    """
    if PRODUCTION:
        default = environ.Env.NOTSET
    return getattr(env, method)(key, default)


# Sets the list of valid HOST header values. Typically this is handled by a reverse proxy in front of the deploy Django application. In development, this is provided by the Caddy reverse proxy.
ALLOWED_HOSTS = [prod_required_env("DJANGO_ALLOWED_HOST", default="*")]

# Parses the DATABASE_URL environment variable into a Django databases dictionary.
db_config = env.db_url(
    "DATABASE_URL", default="postgres://postgres:postgres@database/postgres"
)
DATABASES = {"default": db_config}

# Use int64 pk fields
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = prod_required_env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-=c3mpuvz&l0f&x)^tuqg&vl4w15ae4gffugjy5(t)$x-$@s#sg",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "backend",
    "polls.apps.PollsConfig",
    "debug_toolbar",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
    ),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": prod_required_env("DJANGO_REDIS_CACHE_URL", "redis://cache:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

USE_X_FORWARDED_HOST = True

INTERNAL_IPS = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "debug_toolbar.middleware.show_toolbar_with_docker"
}
