import './globals.css';
import Providers from './providers';
import { Box, Paper, Stack, Typography } from '@mui/material';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'DesignPVP',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ height: '100dvh' }}>
        <Providers>
          <Stack height={'100%'}>
            <Paper sx={{ px: 3, py: 1 }}>
              <Typography variant="h4">DesignPVP</Typography>
            </Paper>
            <Box flexGrow={1}>{children}</Box>
          </Stack>
        </Providers>
      </body>
    </html>
  );
}
