/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Designpvp API
 * artfight clone bluh
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<{ [Q in P]: T[P] }, { -readonly [Q in P]: T[P] }, P>;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (k: infer I) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object ? NonReadonly<NonNullable<T[P]>> : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

export interface Event {
  readonly id: number;
  /** @maxLength 50 */
  name: string;
  starts: string;
  ends: string;
}

export interface PatchedEvent {
  readonly id?: number;
  /** @maxLength 50 */
  name?: string;
  starts?: string;
  ends?: string;
}

export interface PatchedTeam {
  readonly id?: number;
  /** @maxLength 50 */
  name?: string;
  event?: number;
}

export interface Team {
  readonly id: number;
  /** @maxLength 50 */
  name: string;
  event: number;
}

export const eventsList = <TData = AxiosResponse<Event[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/events/`, options);
};

export const eventsCreate = <TData = AxiosResponse<Event>>(
  event: NonReadonly<Event>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, event.name);
  formUrlEncoded.append(`starts`, event.starts);
  formUrlEncoded.append(`ends`, event.ends);

  return axios.post(`/api/events/`, formUrlEncoded, options);
};

export const eventsRetrieve = <TData = AxiosResponse<Event>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/events/${id}/`, options);
};

export const eventsUpdate = <TData = AxiosResponse<Event>>(
  id: number,
  event: NonReadonly<Event>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, event.name);
  formUrlEncoded.append(`starts`, event.starts);
  formUrlEncoded.append(`ends`, event.ends);

  return axios.put(`/api/events/${id}/`, formUrlEncoded, options);
};

export const eventsPartialUpdate = <TData = AxiosResponse<Event>>(
  id: number,
  patchedEvent: NonReadonly<PatchedEvent>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formUrlEncoded = new URLSearchParams();
  if (patchedEvent.name !== undefined) {
    formUrlEncoded.append(`name`, patchedEvent.name);
  }
  if (patchedEvent.starts !== undefined) {
    formUrlEncoded.append(`starts`, patchedEvent.starts);
  }
  if (patchedEvent.ends !== undefined) {
    formUrlEncoded.append(`ends`, patchedEvent.ends);
  }

  return axios.patch(`/api/events/${id}/`, formUrlEncoded, options);
};

export const eventsDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/events/${id}/`, options);
};

export const teamsList = <TData = AxiosResponse<Team[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/teams/`, options);
};

export const teamsCreate = <TData = AxiosResponse<Team>>(
  team: NonReadonly<Team>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, team.name);
  formUrlEncoded.append(`event`, team.event.toString());

  return axios.post(`/api/teams/`, formUrlEncoded, options);
};

export const teamsRetrieve = <TData = AxiosResponse<Team>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/teams/${id}/`, options);
};

export const teamsUpdate = <TData = AxiosResponse<Team>>(
  id: number,
  team: NonReadonly<Team>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, team.name);
  formUrlEncoded.append(`event`, team.event.toString());

  return axios.put(`/api/teams/${id}/`, formUrlEncoded, options);
};

export const teamsPartialUpdate = <TData = AxiosResponse<Team>>(
  id: number,
  patchedTeam: NonReadonly<PatchedTeam>,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  const formUrlEncoded = new URLSearchParams();
  if (patchedTeam.name !== undefined) {
    formUrlEncoded.append(`name`, patchedTeam.name);
  }
  if (patchedTeam.event !== undefined) {
    formUrlEncoded.append(`event`, patchedTeam.event.toString());
  }

  return axios.patch(`/api/teams/${id}/`, formUrlEncoded, options);
};

export const teamsDestroy = <TData = AxiosResponse<void>>(
  id: number,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/teams/${id}/`, options);
};

export type EventsListResult = AxiosResponse<Event[]>;
export type EventsCreateResult = AxiosResponse<Event>;
export type EventsRetrieveResult = AxiosResponse<Event>;
export type EventsUpdateResult = AxiosResponse<Event>;
export type EventsPartialUpdateResult = AxiosResponse<Event>;
export type EventsDestroyResult = AxiosResponse<void>;
export type TeamsListResult = AxiosResponse<Team[]>;
export type TeamsCreateResult = AxiosResponse<Team>;
export type TeamsRetrieveResult = AxiosResponse<Team>;
export type TeamsUpdateResult = AxiosResponse<Team>;
export type TeamsPartialUpdateResult = AxiosResponse<Team>;
export type TeamsDestroyResult = AxiosResponse<void>;
