# Generated by Django 5.2.7 on 2026-07-24 22:42

import django.db.models.deletion
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def merge_duplicate_profiles(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Profile.user used to be a plain ForeignKey, so a user could accumulate several
    profiles. Collapse each user's profiles into their oldest one, folding the team
    memberships of the discarded profiles into the survivor so no membership is lost.
    """
    Profile = apps.get_model("profiles", "Profile")

    duplicated_user_ids = list(
        Profile.objects.values("user_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
        .values_list("user_id", flat=True)
    )

    for user_id in duplicated_user_ids:
        profiles = list(Profile.objects.filter(user_id=user_id).order_by("id"))
        survivor, duplicates = profiles[0], profiles[1:]
        for duplicate in duplicates:
            survivor.teams.add(*duplicate.teams.all())
            duplicate.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_drop_team_users_and_ordering"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="profile",
            name="teams",
            field=models.ManyToManyField(related_name="profiles", to="events.team"),
        ),
        # Must run before user becomes unique, or the AlterField below hits an
        # IntegrityError on any database that already has duplicates.
        migrations.RunPython(merge_duplicate_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
