# Generated by Django 5.2.7 on 2026-07-27 22:29

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_user_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.storage.UploadTo('avatars')),
        ),
    ]
